sumarize_video:
  description: >
    Entrada: {topic}
    Verifique se na entrada informada existe um vídeo. Se sim, resuma o conteúdo do vídeo
    em tópicos principais. Com base no retorno do humano, apenas informe o tópico selecionado.
  expected_output: >
    Tópico informado pelo humano.

search_video:
  description: >
    Vídeo: {topic}
    Use a ferramenta "Busca em transcrições"
  expected_output: >
    Saída da ferramenta "Busca em transcrições".