sumarize_video:
  description: >
    Entrada: {topic}
    Verifique se na entrada informada existe um vídeo. Se sim, resuma o conteúdo do vídeo
    em tópicos principais. Com base no retorno do humano, apenas informe o tópico selecionado.
  expected_output: >
    Tópico informado pelo humano.

search_video:
  description: >
    Entrada: {topic}
    Pesquise no video onde o topico informado é discutido. 
  expected_output: >
    Saída da ferramenta de busca de vídeo.